import os
import re
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
import httpx

from app.database import get_db
from app.models.notification import SMSLog, EmailLog
from app.schemas.report import SMSRequest
from app.notifications import send_health_sms

router = APIRouter(tags=["Notifications & Dispatch"])

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')

@router.post("/notifications/sms")
@router.post("/notifications/send-sms")
@router.post("/send-sms")
def send_sms_report(payload: dict):
    phone = (payload.get("phone") or payload.get("phone_number") or "").strip()
    user_name = payload.get("user_name", "PulseVision User")
    bpm = float(payload.get("bpm", 72.0))
    classification = payload.get("classification", "Normal Range")
    stress_level = payload.get("stress_level", "Low (Relaxed)")
    fatigue_level = payload.get("fatigue_level", "Normal")

    res = send_health_sms(phone, user_name, bpm, classification, stress_level, fatigue_level)
    return res

@router.get("/sms-logs")
def get_sms_logs(db: Session = Depends(get_db)):
    logs = db.query(SMSLog).order_by(SMSLog.timestamp.desc()).limit(25).all()
    return {
        "success": True,
        "logs": [
            {
                "id": l.id,
                "phone": l.phone,
                "message": l.message,
                "status": l.status,
                "carrier_response": l.carrier_response,
                "timestamp": l.timestamp.strftime("%Y-%m-%d %H:%M:%S") if l.timestamp else "N/A"
            }
            for l in logs
        ]
    }

@router.post("/send-email")
def send_email_report(payload: dict, db: Session = Depends(get_db)):
    email = payload.get("email", "").strip()
    user_name = payload.get("user_name", "PulseVision Participant")
    bpm = float(payload.get("bpm", 72.0))
    classification = payload.get("classification", "Normal Resting Heart Rate")
    stress_level = payload.get("stress_level", "Low (Relaxed)")
    fatigue_level = payload.get("fatigue_level", "Normal")
    ear_val = float(payload.get("ear_value", 0.28))
    sqi = payload.get("signal_quality", "High (Optimal)")
    pdf_path = payload.get("pdf_path")

    if not email or not EMAIL_REGEX.match(email):
        return {"success": False, "configured": True, "error": f"Invalid email format: '{email}'"}

    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_email = os.getenv("SMTP_EMAIL", "").strip()
    smtp_password = os.getenv("SMTP_PASSWORD", "").strip()
    smtp_from = os.getenv("SMTP_FROM", f"PulseVision AI Health <{smtp_email}>" if smtp_email else "PulseVision AI Health")

    subject = f"PulseVision Biometric Report - {bpm} BPM ({classification})"

    # If SMTP credentials are not configured, return an honest configuration status
    if not smtp_email or not smtp_password:
        return {
            "success": False,
            "configured": False,
            "error": "Email delivery requires configuration. Please set SMTP_EMAIL and SMTP_PASSWORD in .env.",
            "recipient": email,
            "subject": subject
        }

    # Execute real SMTP delivery
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = smtp_from
        msg["To"] = email

        scan_time = datetime.now().strftime("%Y-%m-%d %I:%M %p")
        text_body = (
            f"PulseVision Health Assessment Report\n\n"
            f"Participant: {user_name}\n"
            f"Date/Time: {scan_time}\n"
            f"Heart Rate: {bpm} BPM ({classification})\n"
            f"Stress Level: {stress_level}\n"
            f"Fatigue Status: {fatigue_level} (EAR: {ear_val:.3f})\n"
            f"Signal Quality: {sqi}\n\n"
            f"Note: Generated by PulseVision non-contact rPPG research prototype. Non-diagnostic."
        )
        msg.attach(MIMEText(text_body, "plain"))

        html_body = f"""<!DOCTYPE html>
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #070b14; color: #e2e8f0; padding: 20px;">
  <div style="max-width: 580px; margin: 0 auto; background: #0d1527; border: 1px solid rgba(0,240,255,0.2); border-radius: 12px; padding: 24px;">
    <div style="border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 16px; margin-bottom: 20px;">
      <h2 style="color: #00f0ff; margin: 0;">PulseVision AI</h2>
      <p style="color: #94a3b8; font-size: 13px; margin: 4px 0 0 0;">Non-Contact rPPG Physiological Assessment</p>
    </div>
    <div style="background: rgba(0,240,255,0.05); border: 1px solid rgba(0,240,255,0.2); border-radius: 8px; padding: 16px; text-align: center; margin-bottom: 20px;">
      <span style="font-size: 40px; font-weight: 800; color: #00f0ff;">{bpm}</span>
      <span style="font-size: 16px; color: #94a3b8;">BPM</span>
      <div style="font-size: 14px; font-weight: 700; color: #00ff9d; margin-top: 4px;">{classification}</div>
    </div>
    <table style="width: 100%; font-size: 14px; border-collapse: collapse; margin-bottom: 20px;">
      <tr><td style="padding: 8px 0; color: #94a3b8;">Participant</td><td style="padding: 8px 0; font-weight: 600; text-align: right;">{user_name}</td></tr>
      <tr><td style="padding: 8px 0; color: #94a3b8;">Assessment Time</td><td style="padding: 8px 0; font-weight: 600; text-align: right;">{scan_time}</td></tr>
      <tr><td style="padding: 8px 0; color: #94a3b8;">Signal Quality</td><td style="padding: 8px 0; font-weight: 600; text-align: right; color: #00ff9d;">{sqi}</td></tr>
      <tr><td style="padding: 8px 0; color: #94a3b8;">Stress Level</td><td style="padding: 8px 0; font-weight: 600; text-align: right;">{stress_level}</td></tr>
      <tr><td style="padding: 8px 0; color: #94a3b8;">Ocular Fatigue</td><td style="padding: 8px 0; font-weight: 600; text-align: right;">{fatigue_level}</td></tr>
    </table>
    <div style="font-size: 11px; color: #64748b; border-top: 1px solid rgba(255,255,255,0.1); padding-top: 14px; text-align: center;">
      PulseVision AI Research System • Remote Photoplethysmography Monitoring<br>
      <em>Disclaimer: This assessment is an automated research estimate and not a medical diagnosis.</em>
    </div>
  </div>
</body>
</html>"""
        msg.attach(MIMEText(html_body, "html"))

        if pdf_path and os.path.exists(pdf_path):
            try:
                with open(pdf_path, "rb") as f:
                    attach = MIMEApplication(f.read(), _subtype="pdf")
                    attach.add_header("Content-Disposition", "attachment", filename=os.path.basename(pdf_path))
                    msg.attach(attach)
            except Exception as e:
                print(f"[!] Warning: Could not attach PDF: {e}")

        server = smtplib.SMTP(smtp_server, smtp_port, timeout=10)
        server.starttls()
        server.login(smtp_email, smtp_password)
        server.sendmail(smtp_email, email, msg.as_string())
        server.quit()

        status_str = "DELIVERED_SMTP"
        details_str = f"Delivered via {smtp_server}:{smtp_port}"

        log = EmailLog(
            to_email=email,
            subject=subject,
            status=status_str,
            response_details=details_str
        )
        db.add(log)
        db.commit()

        return {
            "success": True,
            "configured": True,
            "recipient": email,
            "subject": subject,
            "message": f"Biometric assessment report successfully sent to {email}."
        }
    except Exception as e:
        status_str = "FAILED_SMTP"
        details_str = f"SMTP error: {str(e)}"
        log = EmailLog(
            to_email=email,
            subject=subject,
            status=status_str,
            response_details=details_str
        )
        db.add(log)
        db.commit()

        return {
            "success": False,
            "configured": True,
            "error": f"Failed to deliver email via SMTP: {str(e)}"
        }

@router.post("/notifications/whatsapp")
@router.post("/send-whatsapp")
def send_whatsapp_report(payload: dict):
    """
    WhatsApp Cloud API Integration (Meta Graph API).
    Sends official clinical document or message if credentials are configured in .env.
    If not configured, returns honest status code and instructions without simulating.
    """
    phone = (payload.get("phone") or payload.get("phone_number") or "").strip()
    user_name = payload.get("user_name", "PulseVision Participant")
    bpm = float(payload.get("bpm", 72.0))
    classification = payload.get("classification", "Normal Range")
    stress_level = payload.get("stress_level", "Low (Relaxed)")
    fatigue_level = payload.get("fatigue_level", "Normal")

    clean_phone = re.sub(r'[^0-9+]', '', phone)
    if not clean_phone or len(clean_phone) < 10:
        return {
            "success": False,
            "configured": True,
            "error": f"Invalid recipient phone number: '{phone}'. Provide full country code (e.g. +1234567890)."
        }

    wa_token = os.getenv("WHATSAPP_API_TOKEN", "").strip()
    wa_phone_id = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "").strip()

    summary_text = (
        f"🩺 *PulseVision Physiological Assessment Report*\n\n"
        f"• *Participant:* {user_name}\n"
        f"• *Heart Rate:* {bpm} BPM ({classification})\n"
        f"• *Autonomic Stress:* {stress_level}\n"
        f"• *Ocular Fatigue:* {fatigue_level}\n\n"
        f"_Note: Non-contact rPPG research estimate. Non-diagnostic._"
    )

    if not wa_token or not wa_phone_id:
        return {
            "success": False,
            "configured": False,
            "error": "WhatsApp integration requires configuration. Configure WHATSAPP_API_TOKEN and WHATSAPP_PHONE_NUMBER_ID in .env.",
            "recipient": clean_phone,
            "formatted_message": summary_text
        }

    url = f"https://graph.facebook.com/v18.0/{wa_phone_id}/messages"
    headers = {
        "Authorization": f"Bearer {wa_token}",
        "Content-Type": "application/json"
    }

    body = {
        "messaging_product": "whatsapp",
        "recipient_type": "individual",
        "to": clean_phone.replace("+", ""),
        "type": "text",
        "text": {"body": summary_text}
    }

    try:
        with httpx.Client(timeout=15.0) as client:
            resp = client.post(url, headers=headers, json=body)
            if resp.status_code in (200, 201):
                data = resp.json()
                msg_id = data.get("messages", [{}])[0].get("id", "N/A")
                return {
                    "success": True,
                    "configured": True,
                    "message_id": msg_id,
                    "recipient": clean_phone,
                    "message": f"Clinical assessment report delivered via WhatsApp (Message ID: {msg_id})."
                }
            else:
                return {
                    "success": False,
                    "configured": True,
                    "error": f"WhatsApp API returned error HTTP {resp.status_code}: {resp.text}"
                }
    except Exception as e:
        return {
            "success": False,
            "configured": True,
            "error": f"Network error contacting WhatsApp API: {str(e)}"
        }

@router.get("/email-logs")
def get_email_logs(db: Session = Depends(get_db)):
    logs = db.query(EmailLog).order_by(EmailLog.timestamp.desc()).limit(25).all()
    return {
        "success": True,
        "logs": [
            {
                "id": l.id,
                "to_email": l.to_email,
                "subject": l.subject,
                "status": l.status,
                "response_details": l.response_details,
                "timestamp": l.timestamp.strftime("%Y-%m-%d %H:%M:%S") if l.timestamp else "N/A"
            }
            for l in logs
        ]
    }
